### ISSUE TITLE
replace static profile list with dynamic one

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-app#47]
Currently the list of profiles are hard-coded in [a static TEI document](https://github.com/acdh-oeaw/vicav-content/blob/master/vicav_texts/vicav_explanation_profiles.xml). This should be replaced by a dynamically generated list served by the dedicated endpoint developed for TUNOCENT.

TODO: 
- [x] add grouping level by country (in case there's more than one country in all input profiles)
- [ ] factor out the introduction text

**Comment by MauPalantir** [comment]
Note: the endpoint already exists for Tunocent, it just does not yet support grouping by country.

**Comment by MauPalantir** [comment]
Added the group by country functionality, but the VICAV data currently does not support countries, so the detailed profileDesc needs to be added to the data.


An example header:
```
<profileDesc>
         <taxonomy>
            <category xml:id="featurelist">
               <catDesc>linguistic feature list</catDesc>
            </category>
         </taxonomy>
         <particDesc>
            <person sex="f" age="45">AinDraham11</person>
            <person sex="m" age="50">Tabarka8</person>
            <person sex="f" age="20">AinDraham12</person>
         </particDesc>
         <settingDesc>
            <place>
               <settlement>
                  <name xml:lang="en">Ain Draham</name>
                  <name xml:lang="aeb">ʕĒn Dṛāham</name>
               </settlement>
               <region>Jendouba</region>
               <country>Tunisia</country>
               <location>
                  <geo>36.77, 8.69</geo>
               </location>
            </place>
         </settingDesc>
      </profileDesc>```
      
      where catDesc can be 'linguistic profile', 'linguistic feature list', 'sample text'
