### ISSUE TITLE
initial setup misses menu / project configuration

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/vicav-app#53]
Following the setup steps in README.md, the resulting installation does not have a menu, because the project router file seems to be missing.

the XHR call to http://localhost:8984/vicav/project -H 'Accept: application/xml, text/xml, */*; q=0.01' 

returns

```
Stopped at /home/dschopper/bin/basex/webapp/vicav-app/api-problem.xqm, 207/10:
[basex:restxq] Unexpected node: message="http://basex.org/restxq: Unexpected node: message=""err:FODC0002: Resource '/home/user/bin/basex/webapp/vicav-app/vicav_projects/projects.xml' does not exist."".".
 ```

**Comment by simar0at** [comment]
Seems this is due to a local issue where the vicav-content data is never loaded. This is part of the test process so it is tested on every push.
